### ISSUE TITLE
[SIMULATOR] Implement Health Regen Calculation

### ISSUE THREAD

**Issue by Nostrademous** [pydota2/pydota2_archive#16]
Health Regeneration for units is performed at 0.1 sec ticks (nothing can change this).

Health Regeneration = (Base Regeneration + Sum of Flat Bonuses) × (1 + strength × (5/700)).

Most heroes have a "Base Regeneration" value of 1.5. Check here for exceptions:
https://dota2.gamepedia.com/Health_regeneration#Base_health_regeneration

Tasks to complete this are:
- [ ] Implement a Hero health gain (integer value) on a 0.1 second tick cross-over as part of the simulators step()
- [ ] Implement Health Regeneration function that uses base regen, strength bonus and flat bonus components (for strength it is pure strength from level and strength gain plus strength from item attributes - until we implement items it is best to just placeholder for this)
- [ ] (EVENTUALLY) Implement Ability/Talent bonuses that affect health regen
- [ ] Implement Health Regen for non-hero units and illusions/minions

**Comment by Nostrademous** [comment]
One thing I don't know, by the way, is if unit health is actually a "float" and just displayed as an "integer" in game or if health is always the floor (or ceiling) of the value per tick as affected by regeneration.

**Comment by lenLRX** [comment]
I think it is actually a "float" and just displayed as an "integer".
Otherwise if the health regeneration is less than 1/tick. The HP will keep constant forever.
And I think we'd better keep the design as simple as possible to save our time.
