### ISSUE TITLE
A bit of thought on the project

### ISSUE THREAD

**Issue by Mem3rr0R** [pydota2/pydota2_archive#24]
I‘m thinking that the sc2 api somehow uses game state information directly and use in game instructions( they would be given the instance of the game unit and are able to directly select the game unit without simulating clicks ). So I'm thinking why we would bother simulating human inputs?

**Comment by Nostrademous** [comment]
We are not simulating human peripheral inputs. The plan is for us to directly call appropriate bot API functions to execute the function we want. I still have to enumerate a bunch of them but I'm trying to do so in a very generic way so that I have heavy reuse.

**Comment by Nostrademous** [comment]
Based on my testing, Valve has been doing fixes and changes to the bot-API and just not advertising it or posting anywhere. A bunch of stuff I reported as missing/wrong has been fixed (whether b/c of my reports or other factors; who cares). I have a feeling their tight cooperation with OpenAI is leading to fixes as requested by them directly.

Am I working on this? Good question, I want to and hope to, but my "free" time is very limited currently. I hope to finish up another project I'm working on in the next 1-2 weeks and turn my efforts back to Dota2 botting. 

I've been following the OpenAI-Five work and Benchmark and want to see how well it fairs. OpenAI should be open-sourcing most of their code being a non-profit, so it might be best to wait for that and leverage a large amount of their development.

**Comment by GokulEpiphany** [comment]
That's great to hear, I'm waiting for the day when OpenAI/valve gives us the complete list of BOT APIs. I'm starting out in deep learning field, would love to contribute to Dota (a game where I have spent close to 6k hours). Do keep us updated when you are getting back to this project.
