### ISSUE TITLE
Collaborate

### ISSUE THREAD

**Issue by TimZaman** [pydota2/pydota2_archive#25]
Hi dude, not sure how to contact you, but I've made a DotaService, essentially wrapping dota in an OpenAI Gym environment: https://github.com/TimZaman/DotaService. Currently fully functioning. That should take care of your steps (1) and (2) listed in your readme. I should have my RL agent leaching XP in a few days and hitting creeps well before Christmas!

**Comment by GokulEpiphany** [comment]
Curious..are you in any way related to OpenAi team ?

**Comment by TimZaman** [comment]
Nope just me

**Comment by Nostrademous** [comment]
Awesome, I'll check it out and let you know what I think. General I am very pro community involvement.
